#!/usr/bin/python3

"""
This script is just for automatically generated a CSS file based on the contents
of the 'static/icons' folder
"""

import os

OUTPUT="react-app/public/css/icons.css"

INPUT="react-app/public/icons"

with open(OUTPUT, 'w') as out:
    out.write("/* This file is automatically generated from a script */\n")
    for filename in os.listdir(INPUT):
        url = '/static/icons/' + filename
        name = filename.split('.')[0]
        out.write(".icon_left_" + name + "{background: url('" + url + "') no-repeat left center;}" + "\n")
        out.write(".icon_right_" + name + "{background: url('" + url + "') no-repeat right center;}" + "\n")

